### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by gunjanhshah** [pingidentity/PingID-API-.NET-Sample#1]
I have the developer account on ping identity. when i run this code by passing all the parameters and user name it has asked for it throws error as: The remote server returned an error: (400) Bad Request.

What Am I doing wrong here? Do I have to install and configure PingFederate application on server?

Please help.

Thanks

**Comment by mwhayford** [comment]
I had the exact same issue when using this example. It doesn't appear to work correctly.

**Comment by jessedh** [comment]
did you ever figure this out?

**Comment by mwhayford** [comment]
It was so long ago now , I don't honestly remember. I don't think I did to be honest. Are you having an issue with it?

**Comment by jessedh** [comment]
I am getting the same error using their code sample  (400) Bad Request

**Comment by Diluping** [comment]
I am getting an error using pingid api ,'The remote server returned an error: (400) Bad Request.'

**Comment by yosi1** [comment]
if the userName is not paired with pingid you will get 400. 
make sure that you update  the fields -
org_alias , use_base64_key ,token 
and the requested userName is registered in your organization on PingID
